vocab_size: null
max_seq_len: 1024
d_model: 512
n_layers: 4
n_heads: 4
dropout: 0.1
bias: true
learning_rate: 0.0003
batch_size: 16
eval_interval: 500
eval_iters: 200
device: cpu  # or 'cuda / cpu'
epochs: 10
log_dir: logs
ckpt_dir: checkpoints 
input_txt: data/input.txt 